services:
  - type: web
    name: hrms-app
    env: node
    plan: free
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: DB_HOST
        fromDatabase:
          name: hrms-db
          property: host
      - key: DB_USER
        fromDatabase:
          name: hrms-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: hrms-db
          property: password
      - key: DB_NAME
        fromDatabase:
          name: hrms-db
          property: database

databases:
  - name: hrms-db
    plan: free